name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Site to Amazon S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "^16"
      - run: yarn install --dev
      - run: yarn test
      - run: yarn build
      - name: Push to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "public"

  clean-cdn-cache:
    name: Invalidate Amazon CloudFront Cache
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Determine Updated Files
        run: |
          set +e
          FILES=$(git log --stat="1000" -1 | grep '|' | awk '{print "/"$1}' | grep "public/")
          set -ex
          [ -z "$FILES" ] && touch .updated_files && exit 0
          for file in $FILES; do
            echo $file | sed 's/\/public//'
            [[ "$file" == *"/index.html" ]] && echo $file | sed -e 's/\/index.html$/\//' | sed 's/\/public//'
          done | sort | uniq | tr '\n' ' ' > .updated_files

      - name: Invalidate Amazon CloudFront Global CDN
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS_FROM: .updated_files
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
